name: quickride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  geolocator: ^14.0.2
  dio: ^5.9.1
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  image_picker: ^1.2.1
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  
  # Additional packages
  uuid: ^4.5.1
  intl: ^0.20.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pngs/
    - assets/svgs/

fonts:
  - family: SchibstedGrotesk
    fonts:
      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-Regular.ttf
        weight: 400

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-Medium.ttf
        weight: 500

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-SemiBold.ttf
        weight: 600

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-Bold.ttf
        weight: 700

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-ExtraBold.ttf
        weight: 800

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-Black.ttf
        weight: 900

        # Italic Versions
      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-Italic.ttf
        style: italic

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-MediumItalic.ttf
        weight: 500
        style: italic

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-SemiBoldItalic.ttf
        weight: 600
        style: italic

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-BoldItalic.ttf
        weight: 700
        style: italic

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-ExtraBoldItalic.ttf
        weight: 800
        style: italic

      - asset: assets/fonts/schibstedgrotesk/SchibstedGrotesk-BlackItalic.ttf
        weight: 900
        style: italic